language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install pep257 pytest pep8 coverage pytest-cov coveralls

script:
    - python setup.py install
    - py.test
    - pep257 orcid
    - pep8 orcid

after_success:
    - coveralls

notifications:
    email: false