language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install pep257 pytest pep8

script:
    - pep257 orcid
    - pep8 orcid
    - python setup.py test

notifications:
	email: false