language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pep257 pytest pep8 coverage coveralls html5lib beautifulsoup4 lxml
script:
- pep257 orcid
- pep8 orcid
- coverage run --omit="*/__init__.py" --source orcid setup.py test
- coverage report -m
after_success:
- coveralls
notifications:
  email: false

