language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install pep257 pytest pep8 coverage coveralls

script:
    - pep257 orcid
    - pep8 orcid
    - coverage run --source orcid setup.py test
    - coverage report

after_success:
    - coveralls

notifications:
    email: false